database:
  host: "localhost"#postgres
  user: "postgres"
  password: "test159"
  name: "trading_ace"
  port: 5432
  sslmode: "disable"
  timezone: "Asia/Taipei"

server:
  port: 8080

campaign:
  starttime: "2024-07-24T16:35:00+08:00"

ethereum:
  url: wss://mainnet.infura.io/ws/v3/{your_project_key}