version: '3.8'
services:
    web:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        image: postgres:16
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: test159
            POSTGRES_DB: trading_ace
        ports:
            - "5432:5432"
        volumes:
            - ./schema:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 5s
